#!/usr/bin/env python3
"""Aggregate every Status: header in the vault into one table in Dashboard.md.

Why this exists: every file already declares a Status:, but nothing collected
it, so "what in this vault is actually live?" could only be answered by reading
the whole vault. That question came up twice in one day - once in a full audit,
once from the Telegram worker, which failed it. Roughly a third of the tree is
scaffolding that has never been used, and nothing surfaced that.

Writes between two HTML-comment markers in Dashboard.md, the same pattern
System_Prompt.md already uses for the worker prompt - so the generated block has
a defined boundary and the hand-written parts of the Dashboard are never
touched.

    python3 vault_status.py           # rewrite the block in Dashboard.md
    python3 vault_status.py --check   # exit 1 if the block is stale (no write)
"""
import os
import re
import sys

# .../AI-OS/02_Systems/Automation/vault_status.py -> up three to the vault root
VAULT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DASHBOARD = os.path.join(VAULT, "00_System", "Dashboard.md")
START = "<!-- VAULT_STATUS_START -->"
END = "<!-- VAULT_STATUS_END -->"

SKIP_DIRS = {".git", "node_modules", "__pycache__", ".obsidian", "tasks", "backups"}
# 99_Archive is deliberately excluded: everything in it is archived by
# definition, so listing it would pad the table without informing anything.
SKIP_TOP = {"99_Archive"}

STATUS_RE = re.compile(r"^Status:\s*(.+?)\s*$", re.M)


def bucket(status):
    """Collapse the free-text Status: vocabulary into something countable.

    The vocabulary drifted over 29 sprints - 104 files say plain "Active",
    another ~15 say things like "Active - no entries yet" or "Active - structure
    only". Those distinctions are meaningful and worth keeping in the detail
    rows, but they make a top-line count useless unless grouped."""
    s = status.lower()
    if s.startswith("dormant"):
        return "Dormant"
    if s.startswith("archived") or s.startswith("closed"):
        return "Closed/Archived"
    if s.startswith("accepted"):
        return "Accepted (ADR)"
    if s.startswith("complete"):
        return "Complete"
    if "no entries yet" in s or "structure only" in s or "not yet" in s:
        return "Active (empty)"
    if s.startswith("active"):
        return "Active"
    return "Other"


ORDER = ["Active", "Active (empty)", "Dormant", "Complete",
         "Accepted (ADR)", "Closed/Archived", "Other"]


def scan():
    rows = []
    for root, dirs, files in os.walk(VAULT):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS and not d.startswith(".")]
        rel_root = os.path.relpath(root, VAULT)
        top = rel_root.split(os.sep)[0]
        if top in SKIP_TOP:
            continue
        for fn in files:
            if not fn.endswith(".md"):
                continue
            path = os.path.join(root, fn)
            rel = os.path.relpath(path, VAULT).replace(os.sep, "/")
            try:
                head = open(path, encoding="utf-8", errors="replace").read(2000)
            except OSError:
                continue
            m = STATUS_RE.search(head)
            if m:
                rows.append((rel, m.group(1)))
    return sorted(rows)


def render(rows):
    counts = {}
    for _, status in rows:
        counts[bucket(status)] = counts.get(bucket(status), 0) + 1

    out = [START, "",
           "*Generated by `02_Systems/Automation/vault_status.py` — do not edit by hand.*",
           "", f"**{len(rows)} files declare a Status.**", "",
           "| Bucket | Files |", "|---|---|"]
    for name in ORDER:
        if counts.get(name):
            out.append(f"| {name} | {counts[name]} |")

    dormant = [(p, s) for p, s in rows if bucket(s) == "Dormant"]
    empty = [(p, s) for p, s in rows if bucket(s) == "Active (empty)"]

    if dormant:
        out += ["", "### Dormant — scaffolded but never used",
                "Kept deliberately, not forgotten. Each is a real decision to revisit or archive.", ""]
        out += [f"- `{p}` — {s}" for p, s in dormant]
    if empty:
        out += ["", "### Active but empty — structure exists, no content yet", ""]
        out += [f"- `{p}` — {s}" for p, s in empty]

    out += ["", END]
    return "\n".join(out)


def main():
    rows = scan()
    block = render(rows)
    text = open(DASHBOARD, encoding="utf-8").read()

    if START in text and END in text:
        new = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda _: block,
                     text, flags=re.S)
    else:
        # First run: append the block rather than guessing where it belongs.
        new = text.rstrip() + "\n\n## Vault Status (generated)\n\n" + block + "\n"

    if "--check" in sys.argv:
        if new != text:
            print("Dashboard status block is STALE. Run: python3 vault_status.py")
            return 1
        print("Dashboard status block is current.")
        return 0

    if new == text:
        print("Dashboard already current — no change.")
        return 0
    open(DASHBOARD, "w", encoding="utf-8").write(new)
    print(f"Dashboard updated: {len(rows)} files scanned.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
